apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
        track: stable
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
