version: '3'
services:
  nginx:
    image: nginx
    deploy:
      replicas: 1
      volumes:
      - ./default.conf:/etc/nginx/conf.d
  mongodb:
    image: mongo
    volumes:
    - ./mongod.conf:/etc
  mongoadmin:
    build: 
      context: ../adminMongo/
      dockerfile: DockerMongoAdmin
  redis:
    image: redis
  nodejs:
    image: node
	
	