apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: playground
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: playground
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
        tier: frontend
        track: stable
    spec:
      containers:
      - name: playground
        image: 280500817869.dkr.ecr.us-east-1.amazonaws.com/playground:latest
        ports:
        - containerPort: 8080
        command: ["/bin/bash"]
        args: ["-c", "chmod +x /srv/ops/local/*.* && /srv/ops/local/main.sh"]
