#!/bin/bash

#SERVICE="playground"
#DNS="playground.dev"
COMPOSE_FILE="docker-compose.yml"

compose () {
    docker-compose -f $COMPOSE_FILE build
    docker-compose -f $COMPOSE_FILE up -d
    docker-compose -f $COMPOSE_FILE ps
#    docker-compose -f $COMPOSE_FILE rm --all
}

if [ "$1" == "setup" ]; then
    compose;
    #/usr/bin/open -a "/Applications/Google Chrome.app" "http://$DNS/"
    #/usr/bin/open -a "/Applications/Google Chrome.app" "http://$DNS:8080/debug?port=4001"
elif [ "$1" == "destroy" ]; then
#    removeDNS;
 #   init;
    docker-compose -f $COMPOSE_FILE kill -s SIGINT
  #  destroyMachine;
elif [ "$1" == "shell" ]; then
   # init;
    docker exec -it $(docker-compose -f $COMPOSE_FILE ps -q playground) bash -c "cd /srv;/bin/bash;"
elif [ "$1" == "restart" ]; then
    #init;
    docker exec -it $(docker-compose -f $COMPOSE_FILE ps -q playground) bash -c "cd /srv;pushd ./database;db-migrate up;popd;forever restartall;"
else
    echo "invalid command"
fi
