#!/bin/bash

COMPOSE_FILE="docker-compose.yml"

compose () {
    docker-compose -f $COMPOSE_FILE build
    docker-compose -f $COMPOSE_FILE up -d
    docker-compose -f $COMPOSE_FILE ps
}

if [ "$1" == "setup" ]; then
    compose;
elif [ "$1" == "destroy" ]; then
    docker-compose -f $COMPOSE_FILE kill -s SIGINT
elif [ "$1" == "shell" ]; then
    docker exec -it $(docker-compose -f $COMPOSE_FILE ps -q playground) bash -c "cd /srv;/bin/bash;"
elif [ "$1" == "restart" ]; then
    
    docker exec -it $(docker-compose -f $COMPOSE_FILE ps -q playground) bash -c "cd /srv;pushd ./database;db-migrate up;popd;forever restartall;"
else
    echo "invalid command"
fi
