{
   "kind":"Service",
   "apiVersion":"v1",
   "metadata":{
      "name":"samplenodejsdev",
      "labels":{
         "app":"samplenodejsdev"
      }
   },
   "spec":{
      "ports": [
         {
           "port":8080,
           "targetPort":"http-server"
         }
      ],
      "selector":{
         "app":"samplenodejsdev"
      },
      "type": "LoadBalancer"
   }
}