apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleNodeJSDev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleNodeJSDev
    spec:
      containers:
      - name: playground
        image: 280500817869.dkr.ecr.us-east-1.amazonaws.com/playground
        ports:
        - containerPort: 8080
